export interface IOrganization {
    Organization_Master_Id : string,
    Organization_Code:string,
    Organization_Name:string,
    Industry_Type:string,
    Contact_Person:string,
    Contact_Email:string,
    TAX_UID_Number:string,
    PAN_Number:string,
    CIN_Number:string,
    Website:string,
    Emergency_Email:string,
    Inventory_Start_Date:string,
    Fiscal_Year_Start:string,
    Fiscal_Year_End:string,
    Time_Zone:string,
    Bank_Name:string,
    Branch:string,
    Account_Number:string,
    IFSC_Code:string,
    State:string,
    Billing_Address_Line_1:string,
    Billing_Address_Line_2:string,
    Billing_Location:string,
    Billing_City_District:string,
    Billing_State:string,
    Billing_Country:string,
    Billing_Pincode:string,
    Billing_Phone:string,
    Billing_Email:string,
    Shipping_Address_Line_1:string,
    Shipping_Address_Line_2:string,
    Shipping_Location:string,
    Shipping_City_District:string,
    Shipping_State:string,
    Shipping_Country:string,
    Shipping_Pincode:string,
    Shipping_Phone:string,
    Shipping_Email:string,
    Organization_Image:string,
    Is_Active:string


}
